// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using URL_ShorteningDB;

#nullable disable

namespace URL_Shortening.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225122811_URLDB")]
    partial class URLDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("urls.UrlsEntidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Clicks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlCorta")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("createAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("updateAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UrlMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
